"""
GNSS Physical Constraint Enforcer — clips adversarial examples to
data-driven bounds (mu +/- 6*sigma from training set) with optional
hard-floor enforcement from GNSS physical signal constraints.
"""

import numpy as np
from typing import Optional, Dict, Tuple, List


# Physical bounds in original signal units
# (used for documentation, physical plausibility checks, and unnormalised attacks)
GNSS_PHYSICAL_BOUNDS: Dict[str, Tuple[float, float]] = {
    'doppler':         (-5000.0,    5000.0),   # Hz  — L1 GPS typical range
    'cn0':             (20.0,       55.0),      # dB-Hz
    'c_n0':            (20.0,       55.0),      # dB-Hz (alternate naming)
    'pseudorange':     (0.0,        3.0e7),     # metres (~GPS orbit radius)
    'carrier_phase':   (0.0,        1.0),       # normalised cycles
    'code_phase':      (0.0,        1023.0),    # GPS C/A code chips
    'elevation':       (0.0,        90.0),      # degrees
    'azimuth':         (0.0,        360.0),     # degrees
}

# Keywords that trigger physical bound look-up
_FEATURE_KEYWORD_MAP = {
    'doppler':      'doppler',
    'cn0':          'cn0',
    'c/n0':         'cn0',
    'c_n0':         'c_n0',
    'pseudorange':  'pseudorange',
    'carrier':      'carrier_phase',   # only when 'phase' also present
    'code':         'code_phase',      # only when 'phase' also present
    'elevation':    'elevation',
    'azimuth':      'azimuth',
}


class GNSSConstraintEnforcer:
    """
    Clips normalised adversarial features to data-driven bounds derived
    from the training set, with optional hard-floor enforcement based on
    GNSS physical constraints.

    Usage pattern
    -------------
    1. Call fit(X_train, feature_names) once after StandardScaler.
    2. Call clip_to_gnss_bounds(X_adv) after every attack step.
    """

    def __init__(self, feature_names: Optional[List[str]] = None):
        self.feature_names = feature_names
        # {idx: (min_val, max_val)}  in normalised space
        self.normalised_bounds_ = {}

    # ------------------------------------------------------------------
    def fit(self, X_train: np.ndarray,
            feature_names: Optional[List[str]] = None):
        """
        Derive conservative normalised-space bounds from training data.

        We use [mean - 6σ, mean + 6σ] per feature, which covers essentially
        all physically valid samples while blocking truly impossible values
        generated by aggressive attacks.

        Parameters
        ----------
        X_train      : normalised training set (after StandardScaler)
        feature_names: list of column names (used to tighten bounds using
                       physical limits where known)
        """
        if feature_names is not None:
            self.feature_names = feature_names

        mu = X_train.mean(axis=0)
        sigma = X_train.std(axis=0) + 1e-8

        for i in range(X_train.shape[1]):
            self.normalised_bounds_[i] = (
                float(mu[i] - 6 * sigma[i]),
                float(mu[i] + 6 * sigma[i]),
            )
        return self

    # ------------------------------------------------------------------
    def clip_to_gnss_bounds(self, X: np.ndarray) -> np.ndarray:
        """
        Clip each feature to its normalised bound.

        If fit() has not been called, falls back to [-10, 10] per feature
        (a reasonable default for StandardScaler outputs).

        Parameters
        ----------
        X : np.ndarray (n_samples, n_features) — normalised, post-attack

        Returns
        -------
        np.ndarray — clipped in-place copy
        """
        X_clipped = X.copy()

        for i in range(X.shape[1]):
            if i in self.normalised_bounds_:
                lo, hi = self.normalised_bounds_[i]
            else:
                lo, hi = -10.0, 10.0   # safe fallback
            X_clipped[:, i] = np.clip(X_clipped[:, i], lo, hi)

        return X_clipped

    # ------------------------------------------------------------------
    def validate(self, X: np.ndarray) -> dict:
        """
        Count constraint violations per feature.

        Returns a dict with 'valid' flag and per-feature violation counts.
        """
        violations = {}
        total = 0

        for i, (lo, hi) in self.normalised_bounds_.items():
            below = int((X[:, i] < lo).sum())
            above = int((X[:, i] > hi).sum())
            if below + above > 0:
                name = (self.feature_names[i]
                        if self.feature_names else f'feat_{i}')
                violations[name] = {'below': below, 'above': above}
                total += below + above

        return {'valid': total == 0,
                'n_violations': total,
                'violations': violations}
