"""
GNSS Physical Constraint Enforcer
====================================
Single source of truth for GNSS signal physical bounds.

Used by all attack implementations to ensure adversarial examples
remain physically plausible after perturbation.

Bounds are derived from:
  - Kaplan & Hegarty (2017): Understanding GPS/GNSS, 3rd ed., Artech House.
  - Psiaki & Humphreys (2016): GNSS Spoofing and Detection.
    Proc. IEEE, 104(6), 1258-1270.

Note: all attacks operate in the min-max [0,1] feature space (after MinMaxScaler).
The bounds below are in ORIGINAL physical units and are applied by inverse-
transforming, clipping, then re-transforming — OR by simply clipping the
normalised values to the range they would map to after MinMaxScaler.
MinMaxScaler shifts and scales but does not clip, so extreme values after attack
can be clipped by the NORMALISED equivalents stored in self.normalised_bounds
(set via fit()).  The default clip_to_gnss_bounds() operates in the [0,1] space
using data-driven bounds unless physical bounds are provided. The C/N0~I/Q-power
coupling (fit_coupling / enforce_coupling_phys) is always applied in physical
units, since it encodes a physical relation independent of the feature scaling.
"""

import numpy as np
from typing import Optional, Dict, Tuple, List


# Physical bounds in original signal units
# (used for documentation, physical plausibility checks, and unnormalised attacks)
GNSS_PHYSICAL_BOUNDS: Dict[str, Tuple[float, float]] = {
    'doppler':         (-5000.0,    5000.0),   # Hz  — L1 GPS typical range
    'cn0':             (20.0,       55.0),      # dB-Hz
    'c_n0':            (20.0,       55.0),      # dB-Hz (alternate naming)
    'pseudorange':     (0.0,        3.0e7),     # metres (~GPS orbit radius)
    'carrier_phase':   (0.0,        1.0),       # normalised cycles
    'code_phase':      (0.0,        1023.0),    # GPS C/A code chips
    'elevation':       (0.0,        90.0),      # degrees
    'azimuth':         (0.0,        360.0),     # degrees
}

# Keywords that trigger physical bound look-up
_FEATURE_KEYWORD_MAP = {
    'doppler':      'doppler',
    'cn0':          'cn0',
    'c/n0':         'cn0',
    'c_n0':         'c_n0',
    'pseudorange':  'pseudorange',
    'carrier':      'carrier_phase',   # only when 'phase' also present
    'code':         'code_phase',      # only when 'phase' also present
    'elevation':    'elevation',
    'azimuth':      'azimuth',
}


class GNSSConstraintEnforcer:
    """
    Clips normalised adversarial features to data-driven bounds derived
    from the training set, with optional hard-floor enforcement based on
    GNSS physical constraints.

    Usage pattern
    -------------
    1. Call fit(X_train, feature_names) once after MinMaxScaler.
    2. Call clip_to_gnss_bounds(X_adv) after every attack step.
    """

    def __init__(self, feature_names: Optional[List[str]] = None):
        self.feature_names = feature_names
        # {idx: (min_val, max_val)}  in normalised space
        self.normalised_bounds_ = {}

    # ------------------------------------------------------------------
    def fit(self, X_train: np.ndarray,
            feature_names: Optional[List[str]] = None):
        """
        Derive conservative normalised-space bounds from training data.

        We use [mean - 6σ, mean + 6σ] per feature, which covers essentially
        all physically valid samples while blocking truly impossible values
        generated by aggressive attacks.

        Parameters
        ----------
        X_train      : normalised training set (after MinMaxScaler)
        feature_names: list of column names (used to tighten bounds using
                       physical limits where known)
        """
        if feature_names is not None:
            self.feature_names = feature_names

        mu = X_train.mean(axis=0)
        sigma = X_train.std(axis=0) + 1e-8

        for i in range(X_train.shape[1]):
            self.normalised_bounds_[i] = (
                float(mu[i] - 6 * sigma[i]),
                float(mu[i] + 6 * sigma[i]),
            )
        return self

    # ------------------------------------------------------------------
    def fit_coupling(self, X_phys: np.ndarray, feature_names: List[str],
                     name_i: str = 'i_prompt', name_q: str = 'q_prompt',
                     name_cn0: str = 'cn0_dbhz'):
        """
        Learn the physical C/N0 ~ I/Q-power coupling so an attack cannot set
        C/N0 independently of the prompt correlator power (the two are physically
        linked: C/N0 is estimated from the same I/Q the detector also sees).

        Fits cn0 ~ a + b*log10(i^2 + q^2) on the UNSCALED training set and stores
        the empirical residual band [1st, 99th percentile]. Optional; call after
        fit(). No-op if the three columns are not all present. This is the
        realizability constraint Reviewer #4 asks for; see enforce_coupling_phys.
        """
        self.coupling_ = None
        try:
            ii = feature_names.index(name_i)
            iq = feature_names.index(name_q)
            ic = feature_names.index(name_cn0)
        except (ValueError, AttributeError):
            return self
        logp = np.log10(np.clip(X_phys[:, ii] ** 2 + X_phys[:, iq] ** 2, 1e-9, None))
        cn0 = X_phys[:, ic].astype(np.float64)
        b, a = np.polyfit(logp, cn0, 1)
        resid = cn0 - (a + b * logp)
        self.coupling_ = {
            'i': ii, 'q': iq, 'c': ic, 'a': float(a), 'b': float(b),
            'res_lo': float(np.percentile(resid, 1)),
            'res_hi': float(np.percentile(resid, 99)),
        }
        return self

    def enforce_coupling_phys(self, X_phys: np.ndarray) -> np.ndarray:
        """
        Clip C/N0 (physical units) to stay within the learned residual band of the
        value predicted from the (possibly perturbed) I/Q power, keeping adversarial
        examples on the physically-realizable C/N0~power manifold. Operates on
        UNSCALED features; no-op if fit_coupling was not called. For scaled-space
        attacks, inverse-transform, call this, then re-transform.
        """
        if not getattr(self, 'coupling_', None):
            return X_phys
        c = self.coupling_
        X = X_phys.copy()
        logp = np.log10(np.clip(X[:, c['i']] ** 2 + X[:, c['q']] ** 2, 1e-9, None))
        pred = c['a'] + c['b'] * logp
        X[:, c['c']] = np.clip(X[:, c['c']], pred + c['res_lo'], pred + c['res_hi'])
        return X

    # ------------------------------------------------------------------
    def clip_to_gnss_bounds(self, X: np.ndarray) -> np.ndarray:
        """
        Clip each feature to its normalised bound.

        If fit() has not been called, falls back to [-10, 10] per feature
        (a reasonable default for MinMaxScaler outputs).

        Parameters
        ----------
        X : np.ndarray (n_samples, n_features) — normalised, post-attack

        Returns
        -------
        np.ndarray — clipped in-place copy
        """
        X_clipped = X.copy()

        for i in range(X.shape[1]):
            if i in self.normalised_bounds_:
                lo, hi = self.normalised_bounds_[i]
            else:
                lo, hi = -10.0, 10.0   # safe fallback
            X_clipped[:, i] = np.clip(X_clipped[:, i], lo, hi)

        return X_clipped

    # ------------------------------------------------------------------
    def validate(self, X: np.ndarray) -> dict:
        """
        Count constraint violations per feature.

        Returns a dict with 'valid' flag and per-feature violation counts.
        """
        violations = {}
        total = 0

        for i, (lo, hi) in self.normalised_bounds_.items():
            below = int((X[:, i] < lo).sum())
            above = int((X[:, i] > hi).sum())
            if below + above > 0:
                name = (self.feature_names[i]
                        if self.feature_names else f'feat_{i}')
                violations[name] = {'below': below, 'above': above}
                total += below + above

        return {'valid': total == 0,
                'n_violations': total,
                'violations': violations}
